baseline:
  Dataset: 
    target : dataset.FashionIQDataset.FashionIQDataset
    params :
      dress_types: ['dress','shirt','toptee']
      dim: 256
      data_path: ../data
  VAE:
    target: diffusers.models.AutoencoderKL
    params:
  Unet:
    target: module.ldm.unet_2d_condition.UNet2DConditionModel
    params:
  ControlNet: 
    target: module.ControlNet.ControlNetModel
  Embedding:
    target:
  Pipeline:
    target: 
  Training: 
    resume_path : 'runwayml/stable-diffusion-v1-5'
    output_path : 'model/amdin'
    batch_size : 1
    epoch: 20
    gpus: 2
    accumulation: 1
    learning_rate : 1e-4
    accelerate_conf: none 
